## pytest.ini is a configuration file for pytest, a testing framework for Python
# pytest.ini allows you to specify various settings and options for how pytest should run your tests.

[pytest]
# Suppress specific warnings
filterwarnings = 
    ignore::UserWarning:huggingface_hub                  # Ignore warnings from Hugging Face Hub (symbolic link issues for windows users)

## Optional: Add more pytest options here as needed, such as test paths, markers, etc.

# For example, to specify the directory where tests are located, you can add:
# testpaths = tests

# Add default flags for pytest, such as verbose output:
# addopts = -v

# Set the minimum pytest version required to run the tests:
# minversion = 7.0